# Generated by Django 5.2.8 on 2025-11-25 03:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LastfmUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastfm_username', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('total_scrobbles', models.IntegerField(blank=True, null=True)),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('top_artists', models.JSONField(default=dict)),
                ('top_albums', models.JSONField(default=dict)),
                ('top_tracks', models.JSONField(default=dict)),
                ('recent_tracks', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_lastfm_username', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization_type', models.CharField(max_length=100)),
                ('filters', models.JSONField(blank=True, default=dict, null=True)),
                ('image_file', models.FileField(upload_to='visualizations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite_visualizations', to=settings.AUTH_USER_MODEL)),
                ('lastfm_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='visualizer.lastfmuserprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_visualizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
