# Generated by Django 5.2.8 on 2025-11-30 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastfmuserprofile',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='lastfmuserprofile',
            name='recent_tracks',
        ),
        migrations.RemoveField(
            model_name='lastfmuserprofile',
            name='top_albums',
        ),
        migrations.RemoveField(
            model_name='lastfmuserprofile',
            name='top_artists',
        ),
        migrations.RemoveField(
            model_name='lastfmuserprofile',
            name='top_tracks',
        ),
        migrations.RemoveField(
            model_name='lastfmuserprofile',
            name='total_scrobbles',
        ),
        migrations.AlterField(
            model_name='visualization',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_visualizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
