# Generated by Django 5.2.8 on 2025-12-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_remove_lastfmuserprofile_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualization',
            name='image_file',
        ),
        migrations.AddField(
            model_name='visualization',
            name='plotly_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
