# Generated by Django 5.2.8 on 2025-12-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_remove_visualization_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='visualizations/'),
        ),
    ]
